### ISSUE TITLE
What about a register of all transactions?

### ISSUE THREAD

**Issue by pietrobelligoli** [Rithoshi/Gold1#10]
@marcoovise what do you think of a read register function that returns the historical order of transactions?

**Comment by marcoovise** [comment]
It's a good Idea, I'll do it in my next commit

**Comment by marcoovise** [comment]
Done, now the function "buy_metals" add each transaction to the csv file "register".
You find it on the commit https://github.com/Rithoshi/Gold1/commit/a2c73a81e21f0ab08a533d195f8b7cf4661fe859
