### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by RitaGhilardi** [Rithoshi/Gold1#15]
To improve the security of our software, we could make some improvements to the way we store the credit card information. Why don't we remove the email from the csv file that contains sensitive data? If someone breaks into that database, it will be more difficult to trace the data of a specific person.

**Comment by pietrobelligoli** [comment]
Yes! This is a great idea @Rithoshi. In the final report we will argue how we've decided to treat sensitive data, by explaining also this new improvement.

**Comment by francescasignorello** [comment]
Solved! You can find it here af2e6d20ce66c57dc8c2bd87fdf0e4b8c0bd5025
