### ISSUE TITLE
Fix Input()

### ISSUE THREAD

**Issue by francescasignorello** [Rithoshi/Gold1#16]
I think we should modify the code of add_employee, add_user and log-in to automate the execution of tests on these functions. What do you think?

**Comment by RitaGhilardi** [comment]
Yes, we should do it. I'll fix the tests when you are done with the code of the functions.

**Comment by marcoovise** [comment]
I finished the process modifying the main on commit https://github.com/Rithoshi/Gold1/commit/b6d71ddc64a268a5a6412415a877fd2e7bb1f895
