### ISSUE TITLE
Randomize ID in add_user

### ISSUE THREAD

**Issue by RitaGhilardi** [Rithoshi/Gold1#6]
Can someone help me randomize the ID of new users in function _add_user()_?

**Comment by marcoovise** [comment]
Done 
I created an efficient way to generate random values from 1 to 99999999, it sould be more than enough👍
Link of the commit:
https://github.com/Rithoshi/Gold1/commit/b80d836ee1d33b45c5e36bdc1d2bd93fcb529471
