### ISSUE TITLE
Need inventory.csv and wallet.csv

### ISSUE THREAD

**Issue by pietrobelligoli** [Rithoshi/Gold1#9]
Please @marcoovise add the inventory.csv and wallet.csv, otherwise I cannot merge the get_balance.py file into the main.

**Comment by marcoovise** [comment]
I merged my branch with the main. You find them in the main on commit https://github.com/Rithoshi/Gold1/commit/a2c73a81e21f0ab08a533d195f8b7cf4661fe859
